### ISSUE TITLE
Istio needs extra configuration for jaeger to work.

### ISSUE THREAD

**Issue by paprikaw** [mSvcBench/muBench#22]
Hi team, 

I would like to firstly thank you all for the hard works, it save me a lot of time to construct a microservice sample application. I was trying out deploying the monitoring stack on a on-premise k8s cluster. I found that jaeger is not working out of the box after followed through the manual. No trace data was showing in the jaeger dashboard. I use the following config file for istioctl and solve the problem by adding the `meshConfig.defaultConfig.tracing.zipkin.address`field:
``` yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      tracing:
        zipkin:
          address: zipkin.istio-system:9411 // Added config
        sampling: 50
```
The install script that uses istioctl for installation will be:
``` bash
# Secure .kube
chmod go-r -R ~/.kube/

# Prometherus
kubectl create namespace monitoring
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
helm repo update
helm install prometheus prometheus-community/kube-prometheus-stack -n monitoring

# Prometheus (30000) and Grafana (30001) NodePort Services
kubectl apply -f prometheus-nodeport.yaml -n monitoring
kubectl apply -f grafana-nodeport.yaml -n monitoring

# Istio - Installation
istioctl install -f istio-config.yaml -y # Install istio using istioctl
kubectl apply -f jaeger.yaml

# Jaeger NodePort Service (30002)
kubectl apply -f jaeger-nodeport.yaml

# Istio - Prometheus Integration
kubectl apply -f istio-prometheus-operator.yaml

# Kiali
helm repo add kiali https://kiali.org/helm-charts
helm repo update
helm install \
  -n istio-system \
  -f kiali-values.yaml \
  kiali-server \
  kiali/kiali-server

#Kiali NodePort Service (30003)
kubectl apply -f kiali-nodeport.yaml
```
Above script needs to add istioctl in the uBench docker image. I guess Istioctl is a good tool to have in the uBench image for managing istio lifecycle. If adding istioctl to the uBench image is not perfered, adding above configuration in the istio helm chart will also be a choice.
